### ISSUE TITLE
Eén namespace per skos:ConceptScheme, onafhankelijk van andere namespaces en van namespace der skos:Collections

### ISSUE THREAD

**Issue by mvanbrab** [i-Learn-SKOS/common-conceptschemes#1]
**Rationale**
Hierdoor wordt het mogelijk om een skos:ConceptScheme te publiceren (bijvoorbeeld met Apache Jena) onder de corresponderende graph name. Deze veronderstelling wordt ook gedaan in de configuratie van visualisatietools zoals Skosmos.

**Nu is het zo**

Namespaces zijn georganiseerd per collectie. ConceptScheme URI's zijn arbitrair.

Overzicht van huidige prefixen:
```
@prefix o: <https://data.hetarchief.be/id/onderwijs/> .
@prefix ovak: <https://data.hetarchief.be/id/onderwijs/vak/> .
@prefix oniv: <https://data.hetarchief.be/id/onderwijs/niveau/> .
@prefix osub: <https://data.hetarchief.be/id/onderwijs/subniveau/> .
@prefix ogra: <https://data.hetarchief.be/id/onderwijs/graad/> .
@prefix olee: <https://data.hetarchief.be/id/onderwijs/leerjaar/> .
```

Uittreksel uit huidige vak-norelated-final.skos.ttl:
```
o:vak-scheme a skos:ConceptScheme .
o:vak a skos:OrderedCollection .
ovak:aardrijkskunde a skos:Concept .
```

Uittreksel uit huidige onderwijsstructuur-final.skos.ttl:
```
o:structuur a skos:ConceptScheme .
o:niveau a skos:Collection .
o:subniveau a skos:Collection .
o:graad a skos:Collection, skos:OrderedCollection .
o:leerjaar a skos:Collection, skos:OrderedCollection .
oniv:basisonderwijs a skos:Concept .
usub:lager-onderwijs a skos:Concept .
ogra:lager-1e-graad a skos:Concept .
olee:lager-1e-leerjaar a skos:Concept .
```

**Voorstel**

Namespaces georganiseerd per concept scheme. Afzonderlijke, gemeenschappelijke namespace voor collecties.

Overzicht van voorgestelde prefixen:
```
@prefix ocol: <https://data.hetarchief.be/id/onderwijs/collection/> .
@prefix ovak: <https://data.hetarchief.be/id/onderwijs/vak/> .
@prefix ostr: <https://data.hetarchief.be/id/onderwijs/structuur/> .
```

Uittreksel uit voorgestelde vak-norelated-final.skos.ttl:
```
ovak:_scheme a skos:ConceptScheme .
ocol:vak a skos:OrderedCollection .
ovak:aardrijkskunde a skos:Concept .
```

Uittreksel uit voorgestelde onderwijsstructuur-final.skos.ttl:
```
ostr:_scheme a skos:ConceptScheme .
ocol:niveau a skos:Collection .
ocol:subniveau a skos:Collection .
ocol:graad a skos:Collection, skos:OrderedCollection .
ocol:leerjaar a skos:Collection, skos:OrderedCollection .
ostr:basisonderwijs a skos:Concept .
ostr:lager-onderwijs a skos:Concept .
ostr:lager-1e-graad a skos:Concept .
ostr:lager-1e-leerjaar a skos:Concept .
```

**Comment by mielvds** [comment]
Akkoord! IDs stonden nog niet vast, wachtend op een goede indeling. Ik organiseer het zo!

**Comment by mielvds** [comment]
waarom `ovak:_scheme a skos:ConceptScheme .` en niet gewoon `<https://data.hetarchief.be/id/onderwijs/vak> a skos:ConceptScheme .` ? Of is <https://data.hetarchief.be/id/onderwijs/vak> dan voor SKOSMOS de graphname?

**Comment by mvanbrab** [comment]
Ik gebruik https://data.hetarchief.be/id/onderwijs/vak/ als graph name, naar analogie met de andere Skosmos voorbeelden in de installatie. Jouw ConceptScheme URI vind ik wel mooi, maar die URI valt dan net buiten de namespace die de graph name suggereert. Wij hebben consequent gedaan zoals ik voorstel, maar wat jij voorstelt is wel toegelaten hoor, want het werkt nu wel voor structuur (zie https://ilearn.ilabt.imec.be/Skosmos/exp-ondstruct/nl/), met een ConceptScheme URI die "buiten boord" ligt. Dus als je een sterke voorkeur hebt, go!

**Comment by mielvds** [comment]
goh ja, sterke voorkeur. Ik denk gewoon aan dereferencing waar je zou verwachten dat je bij https://data.hetarchief.be/id/onderwijs/vak een pagina over de thesaurus krijgt

**Comment by mvanbrab** [comment]
Prima
