### ISSUE TITLE
rdfs:label vervangen door skos;prefLabel voor skos:Collection, skos:OrderedCollection en skos:ConceptScheme

### ISSUE THREAD

**Issue by mvanbrab** [i-Learn-SKOS/common-conceptschemes#2]
Dit mag, want skos:prefLabel heeft geen domein; (zie https://www.w3.org/TR/skos-reference, 5.6.1) en is meteen binnen het SKOS vocabularium gebracht voor de gegeven gevallen...

**Comment by mielvds** [comment]
ok!

**Comment by mvanbrab** [comment]
Nog ééntje: o:structuur

**Comment by mielvds** [comment]
verdorie!

**Comment by mielvds** [comment]
done!
