### ISSUE TITLE
In vak-norelated-final.skos.ttl: nog enkele labels waar eerste letter kleine letter mag worden

### ISSUE THREAD

**Issue by mvanbrab** [i-Learn-SKOS/common-conceptschemes#3]
Gevonden:
```
Gesorteerde collectie vakken
Leren leren
Mens en maatschappij
Muzische vorming
Sociale vaardigheden
Wetenschappen en techniek
```

**Comment by mielvds** [comment]
Ik denk dat dit de officiële benamingen zijn; je mag dat niet zomaar aanpassen. Dat is wat ik probeerde aan te kaarten. Maar ik vraag na bij Lander of dit echt een probleem is.

**Comment by mielvds** [comment]
ik vind het nog steeds geen goed idee, want iets naar lowercase brengen is veel gemakkelijker. En soms zijn hoofdletters dus zeer bewust

**Comment by mvanbrab** [comment]
Waar de "officiële benamingen" uitgedeeld worden, zijn ze misschien niet altijd consequent geweest...
Soit, een inhoudelijk detail. Er is zeker een hoofdletter nodig bij de talen, zoals in "Nederlands" of bij sommige afkortingen zoals "ICT". Onze approach was: als ze in een applicatie alles met een hoofdletter willen laten beginnen, dan kunnen ze dat in hun visualisatie met de toupper() van hun programmeertaal; in het omgekeerde geval (wij hoofdletteren alles en zij zouden voor hun smaak alles met een kleine letter willen laten beginnen) zouden ze met hun tolower() onterecht van "Nederlands" "nederlands" maken. Voor wat het waard is...

**Comment by mielvds** [comment]
ok fair enough, ik vind dat je wel een punt hebt. Plus, lander geeft aan dat het ok is. Ik pas het aan!
