### ISSUE TITLE
Benamingen voor leerjaren in kleuteronderwijs: feedback van AHOVOKS afwachten

### ISSUE THREAD

**Issue by mvanbrab** [i-Learn-SKOS/common-conceptschemes#5]
Gevraagd via Lien; antwoord verwerken zodra beschikbaar.

**Comment by mielvds** [comment]
We kunnen dit sluiten?

**Comment by mvanbrab** [comment]
Ik sluit het met het gepaste label. Is niet relevant voor wat we hier afkloppen...
