### ISSUE TITLE
Voeg toe in subniveaus: secundair volwassenenonderwijs

### ISSUE THREAD

**Issue by mvanbrab** [i-Learn-SKOS/common-conceptschemes#6]

**Comment by mvanbrab** [comment]
Hey, ik vind "secundair volwassenenonderwijs" niet terug als subniveau onder niveau "volwassenenonderwijs" en op zelfde hoogte als "basiseducatie"???

![afbeelding](https://user-images.githubusercontent.com/6448245/152821855-ac000f28-1889-4a59-9cfa-41186856b733.png)

**Comment by mielvds** [comment]
@mvanbrab rustig... het is done, maar ik moet de data nog committen :)

**Comment by mvanbrab** [comment]
Ah, sorry. Goe bezig! Ik ben niet gewoon aan jouw workflow. Ik sluit weer...
